name: Meshery UI and Server
on:
  pull_request:
    branches:
      - "master"
    paths-ignore:
      - "docs/**"
      - "mesheryctl/**"
      - "*.md"
      - "*.github/**"
  workflow_dispatch:
    inputs:
      logLevel:
        description: "Log level"
        required: true
        default: "warning"

jobs:
  build-backend:
    name: Backend build
    if: github.repository == 'meshery/meshery'
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-go@v3
        with:
          go-version: "1.19"
          check-latest: true
          cache: true
      
      - uses: actions/cache@v3
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
      
      - name: Run and build go program
        env:
          GOPROXY: "https://proxy.golang.org,direct"
          GOSUMDB: off
          GO1111MODULE: on
        run: go build -tags draft ./server/cmd/main.go ./server/cmd/error.go

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: meshery
          path: ./main
  build-ui:
    name: UI Build
    if: github.repository == 'meshery/meshery'
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 1
      
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ secrets.NODE_VERSION }}
      
      - run: sudo npm i -g npm@7

      - uses: actions/cache@v3
        id: node-cache
        with:
          path: |
            ~/cache
            ~/.cache
            /home/runner/.cache
            !~/cache/exclude
            **/node_modules
            /home/runner/.cache/Cypress
          key: ${{ runner.os }}-node-${{ hashFiles('**/lockfiles') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install dependencies
        run: |
          cd ui
          npm i
          cd ..
          cd provider-ui
          npm i
      - name: build meshery-ui
        run: |
          make build-meshery-ui
      - name: build-provider-ui
        run: |
          make build-provider-ui

  tests-ui:
    needs: [build-ui]
    name: UI Integration Tests
    if: github.repository == 'meshery/meshery'
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v3
        with:
          node-version: ${{ secrets.NODE_VERSION }}

      - run: sudo npm -g npm@7
      
      - uses: actions/cache@v3
        id: node-cache
        with:
          path: |
            ~/cache
            ~/.cache
            /home/runner/.cache
            !~/cache/exclude
            **/node_modules
            /home/runner/.cache/Cypress
          key: ${{ runner.os }}-node-${{ hashFiles('**/lockfiles') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Run tests
        run: |
          cd ui
          npm i
          npm run ci-test-integration
          cd ..
          cd provider-ui
          npm i
          npm test
          cd ..

      - uses: codecov/codecov-action@v3
        with:
          files: ./provider-ui/coverage/coverage-summary.json
          directory: ./provider-ui/coverage/lcov-report
          flags: integrationtests
          fail_ci_if_error: true      

  tests-ui-e2e:
    needs: [build-backend, build-ui]
    name: UI end-to-end tests
    if: github.repository == 'meshery/meshery'
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      
      - uses: actions/checkout@v3
        with:
          repository: layer5io/meshery-consul
          path: ./meshery-consul

      - uses: actions/checkout@v3
        with:
          repository: layer5io/meshery-istio
          path: ./meshery-istio

      - uses: actions/download-artifact@v3
        with:
          name: meshery

      - uses: actions/setup-go@v3
        with:
          go-version: "1.19"
          check-latest: true
          cache: true

      - uses: actions/setup-node@v3
        with:
          node-version: ${{ secrets.NODE_VERSION }}

      - uses: actions/cache@v3
        id: node-cache
        with:
          path: |
            ~/cache
            ~/.cache
            /home/runner/.cache
            !~/cache/exclude
            **/node_modules
            /home/runner/.cache/Cypress
          key: ${{ runner.os }}-node-${{ hashFiles('**/lockfiles') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - uses: helm/kind-action@v1.3.0
        with:
          cluster_name: "kind-cluster"
      
      - name: Build Next.js App
        run: |
          cd ui
          node --version
          npm i
          cd ../
          make build-meshery-ui

      - name: Build meshery-consul
        run: |
          mkdir -p /home/runner/.meshery/bin
          cd ./meshery-consul
          go run main.go &
          sleep 60

      - name: Build meshery-istio
        run: |
          mkdir -p /home/runner/.meshery/bin
          cd ./meshery-istio
          go run main.go &
          sleep 60

      - name: Run backend
        env:
          PROVIDER_BASE_URLS: http:localhost:9876
          PORT: 9081
          ADAPTER_URLS: "localhost:10000 localhost:10001 localhost:10002 localhost:10003 localhost:10004 localhost:10009 localhost:10007"
        run: |
          chmod +x ./main
          ./main &

      - uses: cypress-io/github-action@v4
        with:
          working-directory: ui
          start: npm start
          wait-on: http://localhost:3000
          spec: cypress/integration/e2e/**/*
          record: true
          tag: node-${{ matrix.node }}
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - uses: codecov/codecov-action@v3
        with:
          files: ./ui/coverage/coverage-summary.json
          directory: ./ui/coverage/lcov-report
          flags: e2etests
          fail_ci_if_error: true

  docker-build-test:
    name: Docker build
    if: github.repository == 'meshery/meshery'
    runs-on: ubuntu-22.04
    steps:
      - name: Check out code
        uses: actions/checkout@v3
        with:
          fetch-depth: 1
      
      - name: Docker edge build & tag
        if: startsWith(github.ref, 'refs/tags/') != true && success()
        env:
          RELEASE_CHANNEL: "edge"
        run: |
          DOCKER_BUILDKIT=1 docker build -f install/docker/Dockerfile --no-cache -t meshery:edge-latest --build-arg TOKEN=test --build-arg GIT_COMMITSHA=${GITHUB_SHA::8} --build-arg RELEASE_CHANNEL=${RELEASE_CHANNEL} .
          docker tag meshery:edge-latest meshery:edge-${GITHUB_SHA::8}
      
      - name: Docker edge push
        if: github.event_name != 'pull_request' && startsWith(github.ref, 'refs/tags/') && success()
        run: |
          docker push ${{ secrets.IMAGE_NAME }}:edge-latest
          docker push ${{ secrets.IMAGE_NAME }}:edge-${GITHUB_REF/refs\/tags\//}
          docker push ${{ secrets.IMAGE_NAME }}:edge-${GITHUB_SHA::8}
      
      - name: Docker Hub Description
        if: github.event_name != 'pull_request' && startsWith(github.ref, 'refs/tags/') && success()
        uses: peter-evans/dockerhub-description@v2.0.0
        env:
          DOCKERHUB_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKERHUB_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          DOCKERHUB_REPOSITORY: ${{ secrets.IMAGE_NAME }}