name: Golangci-Lint CI Workflow
on:
  push:
    branches:
      - "master"
    paths:
      - "**.go"
  pull_request:
    branches:
      - "master"
permissions:
  contents: read

jobs:
  golangci:
    strategy:
      matrix:
        go: [1.18, 1.19]
        os: [macos-latest, windows-latest, ubuntu-latest]
    name: golangci-lint
    if: github.repository == 'meshery/meshery'
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go }}
      - uses: actions/checkout@v3
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: latest
